apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-api-service
spec:
  selector:
    app: fraud-detection-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort